/**
 * BACKEND (server-to-server) conversion dispatch to the Soborbo event-gateway.
 *
 * Copy this into the Astro site's `src/lib/tracking/` and call it from the API
 * route that receives the form POST. This is the ONLY way the high-value
 * (`server_ingress_only`) conversions — quote_calculator_submitted,
 * callback_request_submitted, contact_form_submitted, order_request_submitted,
 * purchase — reach the gateway: the browser path answers 403 for them
 * (TRK-400-017), because a browser Origin header is spoofable from curl.
 *
 * This module is battle-tested: it is the exact pattern running in production on
 * lomtalan.hu / painlessremovals.com / beautyflow.hu since Run 6 (2026-07).
 *
 * THE FIVE CONTRACTS THIS ENCODES — breaking any of them is a silent money bug:
 *
 *  1. SERVICE BINDING, not fetch. A plain fetch() to https://<your-site>/api/event/*
 *     would NOT reach the gateway: that URL is a Worker route on your OWN zone, and
 *     Cloudflare short-circuits a Worker subrequest that re-enters a route on the
 *     same zone (loop protection). The lead endpoint still returns 200 — the
 *     conversion just vanishes. Bind the gateway worker in wrangler config:
 *       [[services]]  binding = "GATEWAY"  service = "event-gateway"
 *  2. SHARED event_id. `eventId` MUST be the id the browser minted for this same
 *     conversion (the `event_id` hidden form field). A fresh id does not "add" a
 *     conversion — it DOUBLE-COUNTS the lead, because Meta dedupes on
 *     (event_name, event_id).
 *  3. lead_id is the CRM's id — the `id` from the CRM webhook RESPONSE — or absent.
 *     NEVER substitute a site-side fallback (event_id, email hash, timestamp): a
 *     populated-but-unjoinable lead_id is worse than NULL, because NULL is
 *     detectable and a wrong-namespace key is not.
 *  4. Never send value: 0 — Meta logs it as a real value and it skews ROAS. This
 *     module omits value AND currency together when there is no positive value.
 *  5. 400/401/403/404 are NON-RETRIABLE — they are OUR misconfiguration (bad
 *     payload, bad token, missing KV site-config), and retrying cannot fix them.
 *     Fail loud (log + alert), don't loop.
 *
 * BOT GUARD: when your form endpoint silently fake-succeeds on a honeypot or
 * time-check hit, it must return a `silent: true` flag internally and the caller
 * must SKIP this dispatch (and every other tracking sink). A bot "lead" that books
 * a Meta conversion poisons optimization exactly like a lost real one.
 */

/** Minimal shape of the Cloudflare service binding to the gateway Worker. */
export interface GatewayFetcher {
  fetch: (input: string, init?: RequestInit) => Promise<Response>;
}

export interface GatewayEnv {
  /** Service binding to the event-gateway Worker (see contract #1 above). */
  GATEWAY?: GatewayFetcher;
  /** GA4 measurement id (G-XXXXXXX). Only needed to name the `_ga_<container>`
   * session cookie in `readGa4IdsFromCookie`; the MP send itself is the
   * gateway's job (and only happens for sites with a `ga4` KV block). */
  GA4_MEASUREMENT_ID?: string;
  /** Plaintext per-site token; its SHA-256 is `crm_token_sha256` in the gateway KV
   * site-config (generated by generate-site.mjs → crm-secret.env). */
  TRACKING_GATEWAY_TOKEN?: string;
  /** e.g. https://example.com — the site's own hostname; the gateway resolves the
   * tenant from it (multi-tenant routing). */
  SITE_URL?: string;
  /**
   * A site AKTUÁLIS consent-policy verziója (a böngésző-oldali
   * `PUBLIC_TRACKING_POLICY_VERSION` párja, pl. `2026-08-a`). CSAK a saját CMP-t
   * futtató (`provider: sbo`) site-okon van szerepe.
   *
   * MIÉRT KELL BEÁLLÍTANI: enélkül a szerver-láb elfogadna egy olyan „igen"-t,
   * amit egy KORÁBBI tájékoztató-szövegre adtak, miközben a böngésző-láb
   * ugyanattól a sütitől újrakérdez — a két láb ugyanarról a látogatóról mást
   * gondolna. Hiánya nem hiba (CookieYes-site-okon nincs is értelme), de sbo
   * site-on nyitva hagy egy csendes eltérést.
   */
  TRACKING_POLICY_VERSION?: string;
  /** Synthetic-lead smoke test — see `resolveTestEventCode` + smoke.ts. */
  TRACKING_TEST_LEAD_EMAIL?: string;
  TRACKING_TEST_EVENT_CODE?: string;
}

export type ConsentSignal = 'GRANTED' | 'DENIED';

export interface ConsentState {
  ad_user_data: ConsentSignal;
  ad_personalization: ConsentSignal;
  ad_storage: ConsentSignal;
  analytics_storage: ConsentSignal;
}

/**
 * Canonical gateway event names a site backend may send (Serverside
 * `src/events.json`: channels include "server", kind ≠ offline). The
 * server-ingress-only five are the usual suspects; the click events are legal
 * here too (e.g. an email-click flow confirmed server-side).
 */
export type GatewayEventName =
  | 'quote_calculator_submitted'
  | 'callback_request_submitted'
  | 'contact_form_submitted'
  | 'order_request_submitted'
  | 'purchase'
  | 'phone_number_clicked'
  | 'email_address_clicked'
  | 'whatsapp_button_clicked'
  | 'begin_checkout'
  | 'video_play';

export interface GatewayUserData {
  email?: string;
  phone_number?: string;
  first_name?: string;
  last_name?: string;
  city?: string;
  postal_code?: string;
  country?: string;
}

export interface GatewayConversionInput {
  eventName: GatewayEventName;
  /** MUST be the browser's event_id for this conversion (contract #2). */
  eventId: string;
  /** The CRM's own record id, or absent (contract #3). */
  leadId?: string;
  value?: number;
  /** 3-letter ISO 4217. REQUIRED whenever value is set — there is no default. */
  currency?: string;
  source?: string;
  /**
   * Lead-gen szolgáltatás-címke (pl. `removal`, `clearance`).
   *
   * A BÖNGÉSZŐ-láb (`lib/gateway.ts`) ezt eddig is küldte — a dataLayerre ÉS a
   * `sendToWorker` body-jába —, és a gateway fogyasztja is (`src/lib/ga4.ts`:
   * `params.service`). Csak EBBŐL a lábból hiányzott, tehát a szerver-ingressen
   * érkező konverziók (a CLAUDE.md 10. pontja szerint MINDEN high-value lead)
   * némán elvesztették a címkét, miközben a böngésző-út megtartotta.
   */
  service?: string;
  userData?: GatewayUserData;
  attribution?: Record<string, string | undefined>;
  consent?: ConsentState;
  /** Phase D telemetry — see `buildConsentSources`. Diagnostic only; it does not
   * influence any gate. Pass `buildConsentSources(request.headers.get('cookie'))`. */
  consentSources?: ConsentSourcesPayload;
  /** CMP Fázis 2 (1.3): a döntés-lánc azonosítója (readSboConsentCookieHeader
   * `.consentId`). Az offline/replay ág ezen keresztül oldja fel a consent_log
   * AKTUÁLIS állapotát. CookieYes-site-on hagyd ki — a receipten NULL, nem hiba. */
  consentId?: string;
  eventSourceUrl?: string;
  /** The REAL end-user's IP/UA — without them the gateway would attribute the
   * conversion to our own Worker's egress IP/UA (wrong geo, worse Meta EMQ). */
  clientIpAddress?: string;
  clientUserAgent?: string;
  testEventCode?: string;
  /** GA4 client_id from the browser's `_ga` cookie — see `readGa4IdsFromCookie`.
   * The gateway's MP leg refuses to fire without it (a synthetic id mints a
   * phantom "(not set)" session that pollutes GA4-imported Ads conversions). */
  ga4ClientId?: string;
  /** GA4 session_id from `_ga_<container>`; without it the MP hit is accepted
   * but lands outside the user's session in the reports. */
  ga4SessionId?: string;
  /** Meta `_fbp` / `_fbc` browser cookies — see `readMetaCookies`. Only the site
   * backend sees them (the gateway sits behind a service binding); without fbp
   * the Meta match quality (EMQ) drops even when the email/phone hash is present. */
  fbp?: string;
  fbc?: string;
  /** Ecommerce catalog params (webshop tenants) — validated gateway-side
   * (Serverside lib/ecommerce.ts) and forwarded into Meta custom_data. The ids
   * MUST match the catalog's retailer_id or dynamic remarketing finds nothing. */
  contents?: Array<{ id: string; quantity?: number; item_price?: number }>;
  contentIds?: string[];
  contentType?: 'product' | 'product_group';
  numItems?: number;
  /** The shop's own order id — Meta-side purchase dedup + report join key. */
  orderId?: string;
}

export interface GatewayResult {
  ok: boolean;
  status?: number;
  error?: string;
  retriable?: boolean;
  attempts: number;
}

// Short on purpose: this runs inside the lead request, so a sick gateway must not
// keep the user staring at a spinner. A genuinely lost event is caught by the
// gateway's own zero-conversion / smoke alerts, not by hammering here.
/**
 * A RECEIPTRE KERÜLŐ NYERS SÜTI FELSŐ HATÁRA.
 *
 * A `raw_cookie` a gateway `consent_debug` táblájába megy (14 napos purge), és
 * CSAK akkor, ha a források nem egyeznek. Ettől még nincs okunk a teljes sütit
 * eltenni: a diagnózishoz az eleje elég, a maradék puszta adattöbblet egy
 * consent-jellegű mezőben. A painless fork ezt 200-on tartotta; a kanonikus
 * mag eddig NEM csonkított — ezt a különbséget az F9/3.4 szerver-szelet
 * paritás-futása mutatta ki.
 */
const RAW_COOKIE_MAX = 200;

/**
 * SÜTI-ÉRTÉK DEKÓDOLÁSA, AMI NEM DOBHAT.
 *
 * A `decodeURIComponent` `URIError`-t dob egy hibás percent-szekvenciára
 * (`%zz`, csonka `%E0`). Ez a modul a site LEAD-ÚTVONALÁN fut: az API-route a
 * `readConsentFromCookie(...)` / `buildConsentSources(...)` hívást a konverzió
 * összeállítása közben végzi. Egy dobás ott nem „hiányzó telemetria", hanem
 * 500-as válasz a beküldött űrlapra — az ügyfél leadje vész el egy elrontott
 * süti miatt, amit nem is ő írt.
 *
 * ── KÉT DEGRADÁCIÓ, MERT KÉT KÜLÖNBÖZŐ KÉRDÉS ───────────────────────────────
 * A „ne dobjon" még nem mondja meg, MIRE degradáljon. A két hívó típus mást
 * kíván, és ezt a különbséget a Worker `parseConsentCookieHeader`-e és a
 * painless fork is EGYFORMÁN tartotta — érdemes nem összemosni:
 *
 *   KAPU (`readConsentFromCookie`, `readSboConsentCookieHeader`)
 *       „Milyen hozzájárulásra HIVATKOZHATUNK?" Egy sérült stringből engedélyt
 *       kiolvasni találgatás. Ezért `undefined`/`null` → a gateway a
 *       `require_consent`-re esik vissza és FAIL CLOSED. Ez a helyes GDPR-tartás.
 *
 *   TELEMETRIA (`buildConsentSources`)
 *       „MIT LÁTTUNK?" Itt az eldobás információt semmisít meg: egy hosszú süti
 *       egyetlen hibás escape-je miatt elveszne a mellette álló, tökéletesen
 *       olvasható `advertisement:yes`. A dekódolatlan string RENDSZERINT
 *       ugyanúgy parse-olható (a `kulcs:érték,` alak nem igényel dekódolást),
 *       ezért a telemetria a NYERS értékre esik vissza, és jelent tovább.
 */
function safeDecodeCookieValue(value: string): string | undefined {
  try {
    return decodeURIComponent(value);
  } catch {
    return undefined;
  }
}

/**
 * A TELEMETRIA dekódolója: hibás kódolásra a NYERS értéket adja vissza, nem
 * dob és nem ejt. Lásd a fenti „két degradáció" blokkot — itt a mérés
 * folytonossága a cél, nem a jogalap.
 */
function decodeCookieValueLossy(value: string): string {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}

const DEFAULT_RETRY_DELAYS_MS = [400, 1200];
const defaultSleep = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));

export function gatewayBaseUrl(env: GatewayEnv): string | undefined {
  const raw = env.SITE_URL;
  return raw ? raw.replace(/\/+$/, '') : undefined;
}

export function isGatewayConfigured(env: GatewayEnv): boolean {
  return Boolean(env.TRACKING_GATEWAY_TOKEN && env.GATEWAY && gatewayBaseUrl(env));
}

/**
 * Consent Mode v2 state from the CookieYes cookie — the SAME source, and the same
 * mapping, the browser lib uses (lib/gateway.ts `getConsentState`). Reading it
 * server-side (from the form POST's Cookie header) means the two legs always agree
 * about the user's choice.
 *
 * Returns undefined when the cookie is absent or is not a CookieYes cookie — we do
 * NOT guess. The gateway then applies `require_consent` and fails closed, which is
 * the correct GDPR posture.
 */
export function readConsentFromCookie(
  cookieHeader: string | null,
  opts: SboCookieReadOptions = {}
): ConsentState | undefined {
  if (!cookieHeader) return undefined;

  // CMP Fázis 2: ha a kérésen ott a SAJÁT `sbo_consent` süti (provider='sbo'
  // site), az a döntés forrása — a párhuzamos mérési ablakban a CookieYes sütije
  // is jelen lehet, de a site-ot már a saját CMP hajtja. CookieYes-site-okon a
  // süti nem létezik → az ág bitre a mai.
  const sbo = readSboConsentCookieHeader(cookieHeader, opts);
  if (sbo) {
    const sig = (yes: boolean): ConsentSignal => (yes ? 'GRANTED' : 'DENIED');
    return {
      ad_user_data: sig(sbo.marketing),
      ad_personalization: sig(sbo.marketing),
      ad_storage: sig(sbo.marketing),
      analytics_storage: sig(sbo.analytics),
    };
  }

  let raw: string | undefined;
  for (const part of cookieHeader.split(';')) {
    const idx = part.indexOf('=');
    if (idx < 0) continue;
    if (part.slice(0, idx).trim() === 'cookieyes-consent') {
      raw = safeDecodeCookieValue(part.slice(idx + 1).trim());
      break;
    }
  }
  if (!raw) return undefined;

  const map: Record<string, string> = {};
  for (const part of raw.split(',')) {
    const idx = part.indexOf(':');
    if (idx > 0) map[part.slice(0, idx).trim()] = part.slice(idx + 1).trim();
  }
  if (map.advertisement === undefined && map.analytics === undefined) return undefined;

  const sig = (yes: boolean): ConsentSignal => (yes ? 'GRANTED' : 'DENIED');
  const adGranted = map.advertisement === 'yes';
  return {
    ad_user_data: sig(adGranted),
    ad_personalization: sig(adGranted),
    ad_storage: sig(adGranted),
    analytics_storage: sig(map.analytics === 'yes'),
  };
}

/**
 * CMP Fázis 2 — a saját `sbo_consent` süti szerveroldali olvasata a form-POST
 * Cookie headeréből. A böngésző-lib `consent-sbo-state.ts` parserének párja
 * (formátum: `v1.<a>.<m>.<revision>.<decision>.<consent_id>.<decidedAtSec>`);
 * azért külön implementáció, mert ez a modul önállóan másolódik a site-okra.
 * Bármely mező hibája → null — consentet nem találunk ki.
 */
export interface SboCookieConsent {
  consentId: string;
  analytics: boolean;
  marketing: boolean;
  revision: number;
  decidedAtSec: number;
  /** MELYIK tájékoztató-szöveghez adta a hozzájárulást (v2 mező). */
  policyVersion: string;
}

/**
 * A süti maximális kora másodpercben — a böngésző-lib `SBO_CONSENT_MAX_AGE_S`
 * tükörértéke (180 nap, ICO-ajánlás). A max-age a böngészőben él; egy kézzel
 * visszaírt vagy átvitt süti attól még „frissnek" látszana a szerveren.
 */
export const SBO_CONSENT_MAX_AGE_S = 180 * 24 * 60 * 60;

export interface SboCookieReadOptions {
  /**
   * Ha megadod, a süti policy-verziójának EGYEZNIE kell vele — különben `null`
   * (nincs döntés). A site a saját `PUBLIC_TRACKING_POLICY_VERSION`-jét adja át.
   *
   * MIÉRT KELL ÁTADNI: nélküle a szerver-láb elfogadna egy olyan „igen"-t, amit
   * egy KORÁBBI tájékoztató-szövegre adtak — miközben a böngésző-láb ugyanattól
   * a sütitől újrakérdez. A két láb ugyanarról a látogatóról mást gondolna.
   */
  expectedPolicyVersion?: string;
  /** Tesztelhetőség; alapból a jelen. */
  nowSec?: number;
}

/**
 * A saját `sbo_consent` süti szerveroldali olvasata a form-POST Cookie
 * headeréből.
 *
 * ── MIÉRT KÉZZEL DUPLIKÁLT, ÉS MIÉRT VESZÉLYES ───────────────────────────────
 * Ez a modul ÖNÁLLÓAN másolódik a site-okra, tehát nem importálhatja a
 * böngésző-lib `consent-sbo-state.ts`-ét. A parser így KÉZZEL DUPLIKÁLT párja
 * annak — és pontosan ez a duplikáció csúszott szét: a böngésző-lib áttért a
 * `v2` formátumra (policy-verzióval), ez a parser viszont `v1`-et követelt.
 * Következmény egy `provider: sbo` site-on: MINDEN valódi süti `null`-ra
 * parse-olódott volna, a szerver-láb „nincs döntés"-t látott volna, és
 * `require_consent: true` mellett fail-closed módon KIHAGYTA volna a hirdetési
 * platformokat — némán, minden form-POST konverzión.
 *
 * Négy szabályban kellett utolérnie a böngésző-libet: (1) v2 formátum,
 * (2) policy-verzió egyezés, (3) LEJÁRAT, (4) decision↔kategória konzisztencia.
 * A `consent-backend-parity.test.ts` mostantól UGYANAZON a fixture-táblán
 * futtatja a két parsert, tehát a szétcsúszás nem ismételhető meg némán.
 *
 * A `v1`-es sütit SZÁNDÉKOSAN elutasítjuk — pont úgy, ahogy a böngésző-lib. Egy
 * szerveroldali „még elfogadom a régit" új divergencia lenne, csak a másik
 * irányba.
 */
export function readSboConsentCookieHeader(
  cookieHeader: string | null | undefined,
  opts: SboCookieReadOptions = {}
): SboCookieConsent | null {
  if (!cookieHeader) return null;
  let raw: string | undefined;
  for (const part of cookieHeader.split(';')) {
    const idx = part.indexOf('=');
    if (idx < 0) continue;
    if (part.slice(0, idx).trim() === 'sbo_consent') {
      raw = safeDecodeCookieValue(part.slice(idx + 1).trim());
      break;
    }
  }
  if (!raw) return null;
  const p = raw.split('.');
  if (p.length !== 8 || p[0] !== 'v2') return null;
  if ((p[1] !== '0' && p[1] !== '1') || (p[2] !== '0' && p[2] !== '1')) return null;
  const revision = parseInt(p[3], 10);
  if (!Number.isInteger(revision) || revision < 1 || revision > 10_000 || String(revision) !== p[3]) {
    return null;
  }
  if (!['accept_all', 'reject_all', 'custom', 'withdrawn'].includes(p[4])) return null;
  if (!/^[A-Za-z0-9_:-]{8,64}$/.test(p[5])) return null;
  const decidedAtSec = parseInt(p[6], 10);
  if (!Number.isInteger(decidedAtSec) || decidedAtSec <= 0 || String(decidedAtSec) !== p[6]) {
    return null;
  }
  if (!/^[A-Za-z0-9_:-]{1,64}$/.test(p[7])) return null;
  const policyVersion = p[7];
  // A policy-verzió eltérése NEM „régi, de jó" döntés: más szöveghez adták.
  if (opts.expectedPolicyVersion !== undefined && policyVersion !== opts.expectedPolicyVersion) {
    return null;
  }
  const now = opts.nowSec ?? Math.floor(Date.now() / 1000);
  if (now - decidedAtSec > SBO_CONSENT_MAX_AGE_S) return null;
  const analytics = p[1] === '1';
  const marketing = p[2] === '1';
  // A decision és a kategóriák egymásból következnek — az ellentmondó sütit
  // eldobjuk, ugyanazzal az elvvel, ahogy a gateway 400-at ad rá.
  const matches =
    p[4] === 'accept_all'
      ? analytics && marketing
      : p[4] === 'custom'
        ? analytics !== marketing
        : !analytics && !marketing;
  if (!matches) return null;
  return {
    consentId: p[5],
    analytics,
    marketing,
    revision,
    decidedAtSec,
    policyVersion,
  };
}

/**
 * Phase D (2026-08) consent-source telemetry — the version string every payload
 * reports as `consent_sources.client_lib_version`. Keep in sync with the
 * package version and with the browser lib's `lib/config.ts CLIENT_LIB_VERSION`.
 */
export const BACKEND_LIB_VERSION = '6.6.2';

export interface ConsentSourceSnapshot {
  analytics: boolean | null;
  marketing: boolean | null;
}

export interface ConsentSourcesPayload {
  cookie: ConsentSourceSnapshot;
  api: ConsentSourceSnapshot;
  source_used:
    | 'cookieyes_cookie'
    | 'cookieyes_api'
    | 'override'
    | 'server_cookie'
    | 'sbo_cookie'
    | 'none';
  client_lib_version: string;
  /** A döntés kora másodpercben — CSAK `sbo_consent` alatt (a süti timestampet hordoz). */
  consent_age_s?: number;
  raw_cookie?: string;
}

/**
 * The site backend's OWN reading of the CookieYes cookie, reported to the
 * gateway as telemetry (Phase D). It does NOT change what is sent or gated —
 * `readConsentFromCookie` still produces the `consent` block exactly as before.
 *
 * WHY THE BACKEND MUST REPORT THIS: the gateway is reached over a service
 * binding, so it never sees the end user's Cookie header — on the server ingress
 * its own read is always NULL. Since every high-value conversion (and all nine
 * of the unexplained GRANTED-but-skipped deliveries) travels this path, without
 * this the measurement would be blind exactly where it matters.
 *
 * `null` = that source was not available. Never substitute a default: the NULL
 * pattern is the evidence (a request with no CookieYes cookie at all is the
 * signature of a decision that had not been made or stored yet).
 */
export function buildConsentSources(
  cookieHeader: string | null | undefined,
  opts: SboCookieReadOptions = {}
): ConsentSourcesPayload {
  const unavailable: ConsentSourceSnapshot = { analytics: null, marketing: null };
  // CMP Fázis 2: `sbo_consent` alatt a döntést a saját süti hajtja (source_used
  // + consent_age_s), de a CookieYes-snapshot VÁLTOZATLANUL kitöltődik, ha a
  // sütije jelen van — a párhuzamos mérési ablak (2.4) receipt-oldali evidenciája.
  const sbo = readSboConsentCookieHeader(cookieHeader, opts);
  const sboAge = sbo
    ? Math.max(0, Math.floor(Date.now() / 1000) - sbo.decidedAtSec)
    : undefined;
  let raw: string | undefined;
  if (cookieHeader) {
    for (const part of cookieHeader.split(';')) {
      const idx = part.indexOf('=');
      if (idx < 0) continue;
      if (part.slice(0, idx).trim() !== 'cookieyes-consent') continue;
      raw = decodeCookieValueLossy(part.slice(idx + 1).trim());
      break;
    }
  }
  if (!raw) {
    return {
      cookie: unavailable,
      // There is no browser here, so the CookieYes JS API can never be read.
      api: unavailable,
      source_used: sbo ? 'sbo_cookie' : 'none',
      client_lib_version: BACKEND_LIB_VERSION,
      consent_age_s: sboAge,
    };
  }

  const map: Record<string, string> = {};
  for (const part of raw.split(',')) {
    const idx = part.indexOf(':');
    if (idx > 0) map[part.slice(0, idx).trim()] = part.slice(idx + 1).trim();
  }
  const cookie: ConsentSourceSnapshot = {
    analytics: map.analytics === undefined ? null : map.analytics === 'yes',
    marketing: map.advertisement === undefined ? null : map.advertisement === 'yes',
  };
  const present = cookie.analytics !== null || cookie.marketing !== null;
  return {
    cookie,
    api: unavailable,
    source_used: sbo ? 'sbo_cookie' : present ? 'cookieyes_cookie' : 'none',
    client_lib_version: BACKEND_LIB_VERSION,
    consent_age_s: sboAge,
    // Raw string: the gateway keeps it ONLY when the sources disagree, in the
    // short-lived consent_debug table (14-day purge). Never in consent_receipts.
    raw_cookie: present && raw ? raw.slice(0, RAW_COOKIE_MAX) : undefined,
  };
}

/**
 * Extract the GA4 `client_id` + `session_id` from the form POST's Cookie header.
 *
 * WHY THIS LIVES ON THE SITE AND NOT IN THE GATEWAY: the gateway is reached over a
 * service binding, so it never sees the end user's cookies — only the site backend
 * does. Without this, the gateway's MP leg has no real client_id, and the only
 * alternative (a synthetic/random id) is strictly worse than sending nothing: every
 * hit mints a new GA4 user and a phantom session that GA4 books under
 * Unassigned / "(not set)". On Painless that pattern carried 40% of the key events
 * before it was found (audit 2026-08, P0-A). The gateway therefore SKIPS the MP leg
 * when client_id is absent — this function is what keeps it present.
 *
 *  - `_ga` = `GA1.<scope>.<random>.<timestamp>` → client_id is the trailing
 *    `<random>.<timestamp>` pair, exactly as gtag.js mints it.
 *  - `_ga_<container>` = `GS1.<x>.<session_id>.<count>.<engagement>.<last_active>…`
 *    where `<container>` is the measurement id minus the `G-` prefix.
 *
 * Returns `{}` when a cookie is missing or malformed — we never guess. No analytics
 * consent means no `_ga` cookie, which correctly yields no MP leg.
 */
export function readGa4IdsFromCookie(
  cookieHeader: string | null | undefined,
  measurementId: string | undefined,
): { clientId?: string; sessionId?: string } {
  if (!cookieHeader) return {};

  const cookies: Record<string, string> = {};
  for (const part of cookieHeader.split(';')) {
    const eq = part.indexOf('=');
    if (eq <= 0) continue;
    const k = part.slice(0, eq).trim();
    if (!k) continue;
    cookies[k] = part.slice(eq + 1).trim();
  }

  let clientId: string | undefined;
  const ga = cookies._ga;
  if (ga) {
    const parts = ga.split('.');
    if (parts.length >= 4 && parts[0] === 'GA1') {
      const candidate = `${parts[parts.length - 2]}.${parts[parts.length - 1]}`;
      if (/^\d+\.\d+$/.test(candidate)) clientId = candidate;
    }
  }

  let sessionId: string | undefined;
  if (measurementId) {
    const sessionCookieName = `_ga_${measurementId.replace(/^G-/, '')}`;
    const gaSession = cookies[sessionCookieName];
    if (gaSession) {
      const parts = gaSession.split('.');
      if (parts.length >= 3 && parts[0] === 'GS1' && /^\d+$/.test(parts[2])) {
        sessionId = parts[2];
      }
    }
  }

  return { clientId, sessionId };
}

// Shape guards for the Meta browser cookies — the same regexes the browser lib
// uses, so a truncated/mangled cookie is dropped instead of degrading the event.
const FBP_RE = /^fb\.\d+\.\d+\.\d+$/;
const FBC_RE = /^fb\.\d+\.\d+\.[A-Za-z0-9_-]+$/;

/**
 * Extract the Meta `_fbp` / `_fbc` cookies from the form POST's Cookie header.
 *
 * Same rationale as `readGa4IdsFromCookie`: the gateway never sees the browser's
 * cookies, only the site backend does. `fbp` is the Meta browser id — without it
 * the CAPI event still lands, but match quality (EMQ) drops even when the
 * email/phone hash is present. `fbc` is the click id cookie; when absent the
 * gateway can still derive it from a forwarded `fbclid` attribution param, so
 * missing `_fbc` here is normal and fine.
 */
export function readMetaCookies(
  cookieHeader: string | null | undefined,
): { fbp?: string; fbc?: string } {
  if (!cookieHeader) return {};
  let fbp: string | undefined;
  let fbc: string | undefined;
  for (const part of cookieHeader.split(';')) {
    const eq = part.indexOf('=');
    if (eq <= 0) continue;
    const k = part.slice(0, eq).trim();
    if (k !== '_fbp' && k !== '_fbc') continue;
    const v = part.slice(eq + 1).trim();
    if (k === '_fbp' && FBP_RE.test(v)) fbp = v;
    if (k === '_fbc' && FBC_RE.test(v)) fbc = v;
  }
  // CSAK a ténylegesen meglévő kulcsok. Egy `{ fbc: undefined }` alak nem
  // ugyanaz, mint a hiányzó `fbc`: a hívó `'fbc' in cookies` vagy
  // `Object.keys(...)` ellenőrzése igazat adna egy nem létező klikk-ID-re, és a
  // gateway saját `fbclid → fbc` rekonstrukciója épp ilyenkor maradna ki.
  return { ...(fbp ? { fbp } : {}), ...(fbc ? { fbc } : {}) };
}

/**
 * Returns the Meta test-event code iff this lead is the designated synthetic one.
 * Keyed on the lead's address rather than a global "test mode" flag: a global flag
 * (or the gateway's KV `meta.test_event_code` — FORBIDDEN, see generate-site.mjs)
 * also catches every REAL lead that arrives while it is on, quietly routing paying
 * conversions into Meta's Test stream. Keyed this way, a real lead can never be
 * diverted.
 */
export function resolveTestEventCode(env: GatewayEnv, email?: string): string | undefined {
  const marker = env.TRACKING_TEST_LEAD_EMAIL?.trim().toLowerCase();
  const code = env.TRACKING_TEST_EVENT_CODE?.trim();
  if (!marker || !code || !email) return undefined;
  return email.trim().toLowerCase() === marker ? code : undefined;
}

/** Drops undefined/empty entries so we never ship blank PII fields. */
function compact(obj: object): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v !== undefined && v !== null && v !== '') out[k] = v;
  }
  return out;
}

export function buildGatewayPayload(input: GatewayConversionInput): Record<string, unknown> {
  // Contract #4: never send `value: 0`. Omit value AND currency together when
  // there is no positive money value. Currency has NO default — a hardcoded
  // fallback ships the wrong currency the day the module is copied to a site in
  // another market.
  const hasValue =
    typeof input.value === 'number' && Number.isFinite(input.value) && input.value > 0 &&
    typeof input.currency === 'string' && input.currency.length === 3;

  const userData = input.userData ? compact(input.userData) : undefined;
  const attribution = input.attribution ? compact(input.attribution) : undefined;

  return compact({
    event_name: input.eventName,
    event_id: input.eventId,
    event_time: Math.floor(Date.now() / 1000),
    lead_id: input.leadId,
    ...(hasValue ? { value: input.value, currency: input.currency } : {}),
    source: input.source,
    // Lásd a `service` mező doksiját az inputon: a böngésző-láb eddig is küldte,
    // a gateway fogyasztja; csak innen hiányzott. A `compact()` kihagyja, ha nincs.
    service: input.service,
    user_data: userData && Object.keys(userData).length > 0 ? userData : undefined,
    attribution: attribution && Object.keys(attribution).length > 0 ? attribution : undefined,
    consent: input.consent,
    // Phase D telemetry (optional). Absent → the gateway records NULL sources
    // for this event, which is itself a measurement, not an error.
    consent_sources: input.consentSources,
    // CMP Fázis 2: a consent-lánc azonosítója → consent_receipts.consent_id.
    consent_id: input.consentId,
    event_source_url: input.eventSourceUrl,
    client_ip_address: input.clientIpAddress,
    client_user_agent: input.clientUserAgent,
    test_event_code: input.testEventCode,
    // GA4 stitching ids. Harmless when the site has no `ga4` KV block (the MP leg
    // is a no-op skip there) — but they must travel on the SAME request as the
    // conversion, because the gateway has no other way to learn them.
    client_id: input.ga4ClientId,
    session_id: input.ga4SessionId,
    // Meta browser ids (readMetaCookies) — EMQ; the gateway validates shape again.
    fbp: input.fbp,
    fbc: input.fbc,
    // Ecommerce catalog params (webshop tenants) — gateway-validated, drop-not-
    // reject: a malformed field loses the field, never the purchase.
    contents: input.contents,
    content_ids: input.contentIds,
    content_type: input.contentType,
    num_items: input.numItems,
    order_id: input.orderId,
    // NOTE: no `turnstile_token`. There is no browser in this call path; the
    // per-site X-Admin-Token is what authorises us.
  });
}

export async function sendGatewayConversion(
  env: GatewayEnv,
  input: GatewayConversionInput,
  opts: {
    fetchImpl?: GatewayFetcher['fetch'];
    sleepImpl?: (ms: number) => Promise<void>;
    retryDelaysMs?: number[];
  } = {},
): Promise<GatewayResult> {
  const base = gatewayBaseUrl(env);
  if (!env.TRACKING_GATEWAY_TOKEN || !base || (!env.GATEWAY && !opts.fetchImpl)) {
    return { ok: false, error: 'gateway_not_configured', retriable: false, attempts: 0 };
  }

  const fetchImpl = opts.fetchImpl ?? ((url, init) => env.GATEWAY!.fetch(url, init));
  const sleepImpl = opts.sleepImpl ?? defaultSleep;
  const delays = opts.retryDelaysMs ?? DEFAULT_RETRY_DELAYS_MS;

  // NOT `/api/event/conversion` — that is the BROWSER path (Origin allow-list +
  // IP rate limit). Server-side conversions all leave from a single Worker egress
  // IP, so the IP-keyed limit would throttle exactly the conversions that carry
  // money. The gateway refuses this route without a valid per-site token.
  //
  // We still address the SITE's own hostname (through the service binding): the
  // gateway resolves the tenant from the request hostname.
  const url = `${base}/api/event/conversion-server`;
  const body = JSON.stringify(
    buildGatewayPayload({
      ...input,
      testEventCode: input.testEventCode ?? resolveTestEventCode(env, input.userData?.email),
    }),
  );
  const headers = {
    'content-type': 'application/json',
    'x-admin-token': env.TRACKING_GATEWAY_TOKEN,
  };

  let attempts = 0;
  let lastError = 'unknown';
  let lastStatus: number | undefined;

  for (let i = 0; i <= delays.length; i++) {
    attempts++;
    try {
      const res = await fetchImpl(url, { method: 'POST', headers, body });
      lastStatus = res.status;

      if (res.status >= 200 && res.status < 300) {
        return { ok: true, status: res.status, attempts };
      }

      // Contract #5: 400 (invalid payload), 401 (bad token), 403, 404 (no KV
      // site-config) are OUR misconfiguration, not a transient fault. Retrying
      // cannot fix them — fail loud instead.
      if (res.status === 400 || res.status === 401 || res.status === 403 || res.status === 404) {
        return {
          ok: false,
          status: res.status,
          error: `gateway_rejected_${res.status}`,
          retriable: false,
          attempts,
        };
      }
      lastError = `gateway_status_${res.status}`;
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err);
    }

    if (i < delays.length) await sleepImpl(delays[i]);
  }

  return { ok: false, status: lastStatus, error: lastError, retriable: true, attempts };
}
